# Generated by Django 3.1 on 2020-08-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('phoneno', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
