# Generated by Django 3.1 on 2020-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
