# Generated by Django 3.1 on 2020-09-28 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('customer', '0002_auto_20200928_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='fname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='lname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingcharge', models.IntegerField(default=0)),
                ('totalprice', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=5000)),
                ('bookeddate', models.DateField(default=django.utils.timezone.now)),
                ('deliverydate', models.DateTimeField(default='')),
                ('payment', models.CharField(default='', max_length=200)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.register')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.productsize')),
            ],
        ),
    ]
