# Generated by Django 3.1 on 2020-09-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200928_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housename', models.CharField(default='', max_length=2000)),
                ('nearlocation', models.CharField(default='', max_length=2000)),
                ('cityortown', models.CharField(default='', max_length=2000)),
                ('state', models.CharField(default='', max_length=200)),
                ('pincode', models.CharField(default='', max_length=200)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.register')),
            ],
        ),
    ]
