# Generated by Django 3.1 on 2020-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(default='', max_length=200)),
                ('tokenno', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='orderlist',
            name='orderid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
