# Generated by Django 3.1 on 2020-09-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200929_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='cityortown',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='housename',
            new_name='house',
        ),
    ]
