# Generated by Django 3.1 on 2020-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200930_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='deliverystatus',
            field=models.CharField(default='', max_length=200),
        ),
    ]
