# Generated by Django 3.1 on 2020-10-04 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20201003_2222'),
        ('customer', '0008_customeraddress_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='', max_length=100)),
                ('starpercent', models.IntegerField()),
                ('createdtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.IntegerField()),
                ('delike', models.IntegerField()),
                ('review', models.CharField(default='', max_length=4000)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.register')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.productlists')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likestatus', models.CharField(default='', max_length=50)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.register')),
                ('productreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.productreview')),
            ],
        ),
    ]
