# Generated by Django 3.1 on 2020-10-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_productreview_productreviewlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customername',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='delike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='starpercent',
            field=models.IntegerField(default=0),
        ),
    ]
