# Generated by Django 3.1 on 2020-10-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20201003_2222'),
        ('customer', '0011_auto_20201005_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.productcolor'),
        ),
    ]
