# Generated by Django 3.1 on 2020-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20201001_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommon',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productcommon',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
