# Generated by Django 3.1 on 2020-10-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20201002_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='price',
            field=models.IntegerField(),
        ),
    ]
