# Generated by Django 3.1 on 2020-09-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20200903_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcommon',
            old_name='description',
            new_name='productdetail',
        ),
        migrations.RenameField(
            model_name='productcommon',
            old_name='additionaldescription',
            new_name='stylenote',
        ),
    ]
