# Generated by Django 3.1 on 2020-09-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20200903_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(default='', max_length=200)),
                ('productfulldetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.productsize')),
            ],
        ),
    ]
