# Generated by Django 3.1 on 2020-09-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_productlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='productpicture',
            field=models.ImageField(default='', upload_to='product'),
        ),
    ]
